baseURL = "https://abdelmoumen.com/"
languageCode = "zh-cn"
title = "Amine's blog"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Amine"
  description = "In calm places ,truth reveal."
  github = "amineabdelmoumen"
  twitter = "Amine abdelmoumen"
  linkedin = "amine-abdelmoumen-7936631b"
  email = "abdelmoumen33330@gmail.com"
  url = "https://abdel2333.com"
  keywords = "Java,Spring Boot,Junit"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/github.png"
  location = "Morocco"

  [[params.links]]
    title = "Link"
    href = "https://github.com/amineabdelmoumen"
  [[params.links]]
    title = "Link2"
    href = "https://abdelmoumen.com"
    icon = "https://abdelmoumen/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]